version: "3"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        ports:
            - 1433:1433
        environment:
            SA_PASSWORD: "GVgjR3Wy4j7ZL*2Ay*keT6"
            ACCEPT_EULA: "Y"