apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aspnetcore
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: aspnetcore
    spec:
      containers:
      - name: aspnetcore
        image: danielfe/aspnet2razor
        ports:
        - containerPort: 80
        env:
        - name: Hello
          value: "World!"
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetcore
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: aspnetcore